### ISSUE TITLE
Hid usage does not work after 101

### ISSUE THREAD

**Issue by KINGcrison** [diabolo38/HidKbd#1]
This is just a personal issue for me.I am also trying to make a keyboard with media control. According to the description in the hid manual, usage 130 is exactly increasing the volume, but I modified the logic of the device descriptor to 255, and it still doesn't work. Please help me answer this question

**Comment by diabolo38** [comment]
Your hid desc may be ok with respect to spec but the OS may not like it or is used/expecr to something different  for media control :) 
i think and as far i remenber the media volume control in this hid sample was working.
To be honest i think i copied or extended the generated  hid descpritors from some working  example project  (maybe it was pic based)  maybe you can just do the same see https://github.com/diabolo38/HidKbd/tree/master/Src/usbd_hid.c
they are even some define control to turn on/off led and media so it's quiet easy to see what part of the bytes array is involved and to be added to a basic keybaord .
I also remenber they are some web base  hid desc parser that helped me, that may help you debugging yours ex: http://eleccelerator.com/usbdescreqparser/.

**Comment by KINGcrison** [comment]
Thank you for your help

**Comment by diabolo38** [comment]
welcome i'll closed
